sonar.host.url=http://localhost:9000
sonar.token=sqp_e1ec7873441430abbc3f1204ab7b42c7d74997a9
sonar.projectKey=project-recipes
sonar.projectName=projetoreceitas
sonar.exclusions=media/**, **/migrations/**, **/tests/**, manage.py, project/asgi.py, project/wsgi.py, project/settings.py, utils\recipes\data_factory.py, **/*test*.py
sonar.coverage.exclusions=media/**, **/migrations/**, manage.py, project/asgi.py, project/wsgi.py, project/settings.py, utils\recipes\data_factory.py, **/*test*.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
