# Generated by Django 5.2.3 on 2025-07-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Receita', 'verbose_name_plural': 'Receitas'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(default=None, upload_to='recipes/cover/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prepartion_time_unit',
            field=models.CharField(choices=[('minutos', 'Minutos'), ('horas', 'Horas')], default='minutos', max_length=64),
        ),
    ]
