# Generated by Django 5.2.3 on 2025-07-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(blank=True, default='default/hamburguer.png', upload_to='recipes/cover/%Y/%m/%d/'),
        ),
    ]
